### ISSUE TITLE
tasks for 0.2.0

### ISSUE THREAD

**Issue by ariasanovsky** [ariasanovsky/spindle#23]
- [ ] [`spin!`](https://github.com/ariasanovsky/spindle/issues/4)
- [ ] `DevSpindle/HostSpindle` -> `DevSlice/HostSlice` or better name
- [ ] define `spindle::Result<T>`
- [ ] `cargo doc` cross-platform, on crates.io, etc
- [ ] safety docs
- [ ] resolve the into/try_into safety stuff
- [ ] prohibit `__` and maybe `_` in map names

**Comment by ariasanovsky** [comment]
How do we want to handle

```rust
#[spindle::map(#foo)]
#[spindle::init(#foo)]
fn square_over_two(x: u64) -> f32 {
    ((x * x) / 2) as f32
}
spin!(#foo, U = u64 | f32);
```
We want to be able to
```rust
// initialize a `DevSlice` with `square_over_two` as a method on ranges
let init_nums: DevSlice<U, f32> = (0..).square_over_two(1_000_000)?;
// overwrite existing buffers
let new_slice: DevSlice<U, Uninit> = DevSlice::new(1_000_000)?;
let reused_slice: DevSlice<U, f32> = ((0..), new_slice).square_over_two(1_000_000)?;
//  in-place map
let host_ints: Vec<u64> = (0..1_000_000).collect();
let claimed_ints: DevSlice<U, u64> = host_ints.try_into()?;
let mapped_ints: DevSlice<U, f32> = claimed_ints.square_over_two()?;
```

**Comment by ariasanovsky** [comment]
Example of using a static library (.a) file in a compiled `cu` project:
```bash
nvcc -o cuda_program main.cu path/to/lib.a -L . -lcuda -lcudart_static -arch=sm_60
```
with
```cu
// cu_main.cu
#include <cstdio>
extern "C" float adder(float, float, float);

int main(void)
{
    float result = adder(1.f, 2.f, 3.f);
    printf("%f\n", result);
    return 0;
}
```

**Comment by ariasanovsky** [comment]
[Hey, thanks Yandros](https://users.rust-lang.org/t/how-create-obj-file-from-rust-code-without-core-panic/40441/8?u=ariasanovsky)

# `src/lib.rs`
```rust
src/lib.rs

#![no_std]
#[panic_handler]fn panic(_:&::core::panic::PanicInfo)->!{loop{}}

#[no_mangle] pub unsafe extern "C"
fn suma (a: i32, b: i32) -> i32
{
    a + b
}
```

# `Cargo.toml`
```toml
[lib]
crate-type = [ "staticlib" ] # to generate a `lib<package_name>.a`
                             # i.e. an archive of `.o` files

[package]
name = "foo"
version = "0.1.0"
edition = "2018"

[dependencies] # you may depend on libc if you so wish:
# libc = { version = "*", default-features = false }

[profile.dev]
panic = "abort"
overflow-checks = false

[profile.release]
panic = "abort"
overflow-checks = false
```
